---
version: "3.8"

services:
    flask-app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: kamimadera24/ml-api
        volumes:
            - /data:/data
        ports:
            - "5000:5000"
